add link / unlink methods to hb-service shim

diff --git a/deb/opt/homebridge/hb-service-shim b/deb/opt/homebridge/hb-service-shim
--- a/deb/opt/homebridge/hb-service-shim
+++ b/deb/opt/homebridge/hb-service-shim
@@ -92,6 +92,74 @@ case "$1" in
     exec sudo --user $SHELL_USER env "HOME=$SHELL_USER_HOME" bash --rcfile /opt/homebridge/source.sh -ci "$pnpm_cmd"
     ;;
 
+  "link")
+    check_shell_user_override
+    target_dir="$(pwd)"
+    if [ "$target_dir" = "/var/lib/homebridge" ]; then
+      echo "Error: Cannot run link command in /var/lib/homebridge"
+      exit 1
+    fi
+
+    if [ ! -f "$target_dir/package.json" ]; then
+      echo "Error: Target directory ($target_dir) does not contain a package.json file."
+      exit 1
+    fi
+
+    package_name=$(cat "$target_dir/package.json" | jq -r '.name')
+    if [ "$?" != 0 ] || [ "$package_name" = "null" ]; then
+      echo "Error: Could not read plugin name in package.json"
+      exit 1
+    fi
+
+    target_link="/var/lib/homebridge/node_modules/$package_name"
+    target_dirname="$(dirname $target_link)"
+
+    if [ ! -d "$target_dirname" ]; then
+      mkdir -p $target_dirname
+      chown -h $SHELL_USER: $target_dirname
+    fi
+
+    if [ -e "$target_link" ]; then
+      if [ "$(realpath $target_link)" = "$target_dir" ]; then
+         echo "Error: $package_name is already linked. Run 'hb-service unlink'"
+         exit 1
+      fi
+    fi
+
+    ln -sf "$target_dir" "$target_link"
+    chown -h $SHELL_USER: "$target_link"
+    if [ "$?" = "0" ]; then
+      echo "Success: $package_name linked"
+    fi
+    ;;
+
+  "unlink")
+    check_shell_user_override
+    target_dir="$(pwd)"
+    if [ "$target_dir" = "/var/lib/homebridge" ]; then
+      echo "Error: Cannot run unlink command in /var/lib/homebridge"
+      exit 1
+    fi
+    if [ ! -f "$target_dir/package.json" ]; then
+      echo "Error: Target directory ($target_dir) does not contain a package.json file."
+      exit 1
+    fi
+    package_name=$(cat "$target_dir/package.json" | jq -r '.name')
+    target_link="/var/lib/homebridge/node_modules/$package_name"
+    if [ "$?" != 0 ] || [ "$package_name" = "null" ]; then
+      echo "Error: Could not read plugin name in package.json"
+      exit 1
+    fi
+    if [ ! -e "$target_link" ]; then
+       echo "Error: $package_name is not linked."
+       exit 1
+    fi
+    rm -rf "/var/lib/homebridge/node_modules/$package_name"
+    if [ "$?" = "0" ]; then
+      echo "Success: $package_name unlinked"
+    fi
+    ;;
+
   "logs")
     exec tail -n 100 -f /var/lib/homebridge/homebridge.log
     ;;
@@ -121,6 +189,9 @@ case "$1" in
       "    stop                             stop the homebridge service" \
       "    restart                          restart the homebridge service" \
       "    add <plugin>@<version>           install a plugin" \
+      "    remove <plugin>@<version>        remove a plugin" \
+      "    link                             adds the current directory to Homebridge for plugin development" \
+      "    unlink                           reverses the link operation for the current directory" \
       "    remove <plugin>@<version>        remove a plugin" \
       "    update-node [version]            update Node.js" \
       "    logs                             tails the homebridge service logs" \
