Update preinst

diff --git a/deb/debian/preinst b/deb/debian/preinst
--- a/deb/debian/preinst
+++ b/deb/debian/preinst
@@ -79,13 +79,13 @@ if [ "$1" = "upgrade" ] && [ $2 ]; then
   echo "Running pre-upgrade steps..."
 
   # make sure the package is not being upgraded using the Homebridge UI integrated terminal
-  pstree -s $$ | grep "hb-service" > /dev/null
-  if [ "$?" -eq 0 ]; then
-    echo
-    >&2 echo "ERROR: The homebridge package must not be upgraded from the Homebridge UI Terminal."
-    echo
-    exit 1
-  fi
+#  pstree -s $$ | grep "hb-service" > /dev/null
+#  if [ "$?" -eq 0 ]; then
+#    echo
+#    >&2 echo "ERROR: The homebridge package must not be upgraded from the Homebridge UI Terminal."
+#    echo
+#    exit 1
+#  fi
  
   # stop homebridge.service if it is running
   if systemctl is-active --quiet homebridge.service; then
