Allow running from inside hb-service

diff --git a/deb/debian/preinst b/deb/debian/preinst
--- a/deb/debian/preinst
+++ b/deb/debian/preinst
@@ -5,13 +5,13 @@ if [ "$1" = "install" ]; then
   echo "Running pre-install steps..."
 
   # make sure the package is not being installed using the Homebridge UI integrated terminal
-  pstree -s $$ | grep "hb-service" > /dev/null
-  if [ "$?" -eq 0 ]; then
-    echo
-    >&2 echo "ERROR: The homebridge package must not be installed from the Homebridge UI Terminal."
-    echo
-    exit 1
-  fi
+  #pstree -s $$ | grep "hb-service" > /dev/null
+  #if [ "$?" -eq 0 ]; then
+  #  echo
+  #  >&2 echo "ERROR: The homebridge package must not be installed from the Homebridge UI Terminal."
+  #  echo
+  #  exit 1
+  #fi
 
   # remove the hb-service generated fix-permission pre-start script (fresh install only!)
   if [ -z $2 ] && [ -f /etc/hb-service/homebridge/prestart.d/10-fix-permissions ]; then
