Tweaks

diff --git a/.github/workflows/release-stage-1_update_dependencies.yml b/.github/workflows/release-stage-1_update_dependencies.yml
--- a/.github/workflows/release-stage-1_update_dependencies.yml
+++ b/.github/workflows/release-stage-1_update_dependencies.yml
@@ -54,7 +54,7 @@ jobs:
     steps:
       - name: Run Homebridge ${{ matrix.release_type }} Bot
         id: homebridge-bot
-        uses: NorthernMan54/Homebridge-Dependency-Bot@latest
+        uses: NorthernMan54/Homebridge-Dependency-Bot@latest 
         with:
           config_file: ${{ matrix.config_file }}
           release_stream: ${{ matrix.release_type }}
@@ -71,7 +71,7 @@ jobs:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
           echo "::notice::Triggering ${{ matrix.release_type }} Stage 2 - Build and Release ${{ matrix.release_type }} Package"
-          gh workflow run ${{ matrix.trigger_workflow }} --ref latest || { echo "::error::Failed to trigger ${{ matrix.release_type }} Stage 2 workflow"; exit 1; }
+          gh workflow run ${{ matrix.trigger_workflow }} --ref latest --field release_type=${{ matrix.release_type }} || { echo "::error::Failed to trigger ${{ matrix.release_type }} Stage 2 workflow"; exit 1; }
 
       - name: Checkout repository (for trigger step)
         if: steps.homebridge-bot.outputs.changes_detected == 'true' && steps.homebridge-bot.outputs.auto_merge == 'true'
